BEGIN TRANSACTION;
DROP TABLE IF EXISTS question_vote;
DROP TABLE IF EXISTS answer_vote;
DROP TABLE IF EXISTS saved_question;
DROP TABLE IF EXISTS answer;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS user;
COMMIT;